apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: apache-s2i
    name: apache-s2i
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apache-s2i:latest
        namespace: tmp
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/maci0/apache-s2i.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: tmp/base-centos7:latest
      type: Docker
    triggers:
    - github:
        secret: OmFOWQKh4wh3fzESA78W
      type: GitHub
    - generic:
        secret: JyP1XXSGdf8ZNy1vfURf
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    generation: 1
    labels:
      build: apache-s2i
    name: apache-s2i
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.0.14:5000/tmp/apache-s2i:latest
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
kind: List
metadata: {}
