apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
    name: apache-s2i
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apache-s2i:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/maci0/apache-s2i.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: tmp/base-centos7:latest
      type: Docker
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: apache-s2i
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.0.14:5000/tmp/apache-s2i:latest
      generation: null
      importPolicy: {}
      name: latest
kind: List
